### ISSUE TITLE
Implement STUN/UDP hole punching strategy

### ISSUE THREAD

**Issue by gordonwritescode** [gordonwritescode/kad-traverse#1]
Consider https://github.com/nicojanssens/stun-js

**Comment by nicojanssens** [comment]
Will extend the stun-js lib w hole punching example.

**Comment by gordonwritescode** [comment]
Thanks, that'd be super helpful!

**Comment by gordonwritescode** [comment]
@nicojanssens once i receive a response from the STUN server with my reflexive address, am i correct to assume that i need to check to make sure that the NAT will allow other connections to address me via that address?

Is it a reasonable solution to, upon receipt of my reflexive address, to open a new socket and attempt to send a message to it? I tried that in my console and I get back my reflexive address, but I don't get messages from a second socket on my local machine when sent to the server reflexive address of my first socket.

**Comment by nicojanssens** [comment]
@gordonwritescode I got some basic UDP hole punching working, and was able to exchange messages between a VM on EC2 and a RPI located behind my home NAT.

This does not involve STUN so far. For now, both peers have to know each other's public IP address and port number. I will do some more experiments first, to make sure this code is properly tested before throwing it over the wall.

Next step will be to combine this with STUN to determine a peer's public address and port number.

**Comment by gordonwritescode** [comment]
I have the code written for STUN based hole punching and TURN relay setup, but I'm debugging a strange EINVAL error coming from Node on socket.send. It works in the REPL so I suspect I've got a some issue with socket binding and the event loop. Will continue to work on it today.

**Comment by gordonwritescode** [comment]
I'm still wrestling with this EINVAL issue (coming from the underlying call that node makes in stun-js here: https://github.com/nicojanssens/stun-js/blob/master/src/stun_socket.js#L128)

It has to be something related to my implementation, check it:

![screenshot-20151230-11 03 12](https://cloud.githubusercontent.com/assets/1188875/12053276/624a4506-aee5-11e5-971f-8e02cbb8ad47.png)

The code producing the output on the left effectively does the same thing as the code producing the output on the right. This `Error: send EINVAL` is coming from Node's native call here: https://github.com/nodejs/node/blob/4b267df93ee602bab290a379c0ccfe9b2c4b77a6/lib/dgram.js#L325

Any ideas? o_O

**Comment by gordonwritescode** [comment]
Damn, okay, I have narrowed it down to my `Socket` object. If I don't pass in a socket, I get back my server reflexive address. I'm not sure what is different about my socket that is causing the issue yet.

**Comment by nicojanssens** [comment]
Not sure if I can offer any proper help here -- remote debugging is a pita ...

Btw, can you print and compare the status/internals of a new `Socket` object w the one you keep at `transport._socket`?

**Comment by gordonwritescode** [comment]
Okay, I don't know why yet, but removing the address binding in the socket passed in fixes the problem. 

```js
// this._socket.bind(this._contact.port, this._contact.address, done);
this._socket.bind(this._contact.port, done);
```

Now I've got an issue in the TURN strategy ._.

```
{ method: 3,
  type: 272,
  attrs: 
   { attrs: 
      [ { code: 437,
          reason: 'Mismatched allocation: wrong transaction ID\u0000',
          type: 9 },
        { description: 'Coturn-4.2.1.2 \'Monza\'', type: 32802 } ] },
  tid: 2104510037 }
error: [libstun] no handler available to process response with tid 2104510037
/home/gordon/Code/kad-traverse/node_modules/stun-js/src/stun_socket.js:198
    throw new Error(errorMsg)
    ^

Error: [libstun] no handler available to process response with tid 2104510037
    at StunSocket.onIncomingStunResponse (/home/gordon/Code/kad-traverse/node_modules/stun-js/src/stun_socket.js:198:11)
    at Socket.<anonymous> (/home/gordon/Code/kad-traverse/node_modules/stun-js/src/stun_socket.js:172:16)
    at emitTwo (events.js:92:20)
    at Socket.emit (events.js:172:7)
    at UDP.onMessage (dgram.js:481:8)
```

Marching forward into the abyss...

**Comment by nicojanssens** [comment]
Apparently your TURN server is complaining about an allocate request. And that error response does not match w a request id. So both symptoms are related to the same problem.

Is the available code of your turn up to date? That would help me reproducing this error.

Btw -- did you manage to execute my turn example scripts? See https://github.com/nicojanssens/turn-js/blob/master/examples/channel_data.js

**Comment by gordonwritescode** [comment]
Hey sorry, the above was my bad - I was passing the socket off to the TURN strategy after it failed from the STUN strategy and didn't clean up, which created a weird state where the sma socket was being used by a defunct StunSocket and a new TurnSocket.

I fixed the exception but I still get the `Error: [libturn] allocate error: Mismatched allocation: wrong transaction ID`.

The code here is not up to date, my workspace is a mess. Let me clean it up and also run the examples against my coturn server and see what I get.

**Comment by gordonwritescode** [comment]
Both examples you have work with the turn server i setup, so my code is still bonkers.

**Comment by gordonwritescode** [comment]
Okay, I was able to fix it by not passing the socket to turn-js, now I have to figure *why*.

**Comment by gordonwritescode** [comment]
All working, examples soon!

**Comment by nicojanssens** [comment]
:thumbsup:
